### PR TITLE
Changes to have more generic project files

### PR DESCRIPTION
**Pull request by Jj0YzL5nvJ**
https://github.com/mupen64plus/mupen64plus-core/pull/694

### CODE REVIEW

**Comment by Jj0YzL5nvJ** [comment]
P.S: From LF to CRLF

**Comment by Narann** [comment]
> P.S: From LF to CRLF

I think all others are LF, shouldn't we stay in LF?

**Comment by Gillou68310** [comment]
@Jj0YzL5nvJ Current vcxproj is already CRLF.

**Comment by Jj0YzL5nvJ** [comment]
Look at your answers, `git` is clearly oversmarting you! _(experience talking)_

https://github.community/t5/GitHub-Actions/git-config-core-autocrlf-should-default-to-false/td-p/30445

[I'm not the first one at discover it...](https://github.com/mupen64plus-ae/mupen64plus-rsp-cxd4/commit/74268afb9c5023e0c31fe4b179d1e738d573cd28#diff-93491406f3242340a8685ca2ab9cae81)

BTW, the same thing goes for `osal_dynamiclib_win32.c`

**Comment by Jj0YzL5nvJ** [comment]
Credits to @ecsv for `.gitattributes`, and my evidence of why it's necessary:

<details>
  <summary>Terminal</summary>
  
</details>

<details>
  <summary>Command Prompt</summary>
  
</details>

**Pull request merged**
